### ISSUE TITLE
Run menuconfig

### ISSUE THREAD

**Issue by NiQ1** [raspberry-vanilla/android_kernel_manifest#10]
Please add a way of running menuconfig before compiling. I assume one of the main reasons people download this is to compile a module that is not enabled by default.

**Comment by KonstaT** [comment]
AFAIK this has never really been an option for Android since we're cross compiling for a specific target (at least I've never used it in my 10+ years of doing this).

You just need to modify the defconfig like adults.
https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/arch/arm64/configs/android_rpi4_defconfig
https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/arch/arm64/configs/android_rpi5_defconfig
